# URL settings for yasslab.jp
permalink: /:title
url: https://yasslab.jp

# URL settings for News
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /ja/news/:title

# Use sass for designing
sass:
  style:     compact
  sass_dir:  css
  sourcemap: always
  load_paths:
    - node_modules

# Variables for pages, news, feeds, etc
company:
  vision: "Having a Good Life by Creating ;)"
  size: 8
  email: info@yasslab.jp
  capital: 500
  name:  YassLab

# Variables to configure RSS feed
authors:
  yasulab:
    name: yasulab
    uri:  https://twitter.com/yasulab
  Yuppyhappytoyou:
    name: Yuppyhappytoyou
    uri:  https://twitter.com/Yuppyhappytoyou

# Settings for Jekyll/Heroku hosting
domain:   "yasslab.jp"
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

# Show upcoming news (but hidden in production)
future: true

## Global Vars to generate links
yasslab:       "[YassLab](https://yasslab.jp/)"
railstutorial: "[Railsチュートリアル](https://railstutorial.jp/)"
railsguides:   "[Railsガイド](https://railsguides.jp/)"
coderdojo:     "[coderdojo.jp](https://coderdojo.jp/)"
okinawarb:     "[Okianwa.rb](https://ruby.okinawa/)"
frogs:         "[Ryukyufrogs](https://www.ryukyu-frogs.com/)"

highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids      : true
  autolink      : true
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  input         : GFM
  gfm_quirks    : paragraph_end
  hard_wrap     : true
  footnote_nr   : 1
  show_warnings : false

plugins:
  - jekyll-feed
  - kramdown
  - jekyll-include-cache
  - jekyll-sitemap # This must be LAST to include contents generated by gems above

# Need to declare to include for Netlify
# https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file
include:
  - _redirects

exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - node_modules
  - package.json
  - package-lock.json
  - test
  - spec
  - tasks
  - .jekyll-cache

# Enable Incremental Regeneration feature (experimental)
# https://jekyllrb.com/docs/configuration/incremental-regeneration/
#
# Disabled; needed to rebuild all pages to show future news
# But you can enable this feature by adding '--incremental' option.
incremental: false
